### ISSUE TITLE
[Bug] v4.0  jumpserver-jms-chen-cc88cd989-57dp4      0/1     CrashLoopBackOff

### ISSUE THREAD

**Issue by tanguofu** [jumpserver/helm-charts#158]
**JumpServer 版本(v1.5.9以下不再支持)**

**浏览器版本**

**Bug 描述**

**Bug 重现步骤(有截图更好)**
1.   使用最新的 helm charts 部署安装, chen 组件crash:
```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'messageSource' defined in class path resource [org/jumpserver/chen/web/config/LocaleConfig.class]: Failed to instantiate [org.springframework.context.Mes
sageSource]: Factory method 'messageSource' threw exception with message: I/O error on GET request for "http://core:8080/api/v1/settings/i18n/chen/": core
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1337) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1167) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:337) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:335) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.8.jar!/:6.1.8]
        at org.springframework.context.support.AbstractApplicationContext.initMessageSource(AbstractApplicationContext.java:816) ~[spring-context-6.1.8.jar!/:6.1.8]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:612) ~[spring-context-6.1.8.jar!/:6.1.8]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.0.jar!/:3.3.0]
        at org.jumpserver.chen.web.WebDbApplication.main(WebDbApplication.java:15) ~[!/:0.0.1]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[chen.jar:0.0.1]
        at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[chen.jar:0.0.1]
        at org.springframework.boot.loader.launch.JarLauncher.main(JarLauncher.java:58) ~[chen.jar:0.0.1]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.context.MessageSource]: Factory method 'messageSource' threw exception with message: I/O error on GET request for "http://core:8080/a
pi/v1/settings/i18n/chen/": core
```

**Comment by liuhe-trec** [comment]
我也遇到了同样的问题

**Comment by wojiushixiaobai** [comment]
- https://github.com/jumpserver/chen/issues/5

**Comment by Aaron3S** [comment]
已修复
